### ISSUE TITLE
Where is the ROM?

### ISSUE THREAD

**Issue by gabrielecaruso** [GMMan/flipperzero-tamagotch-p1#1]
Hello,
i read "Create a tama_p1 folder in your microSD card, and put the ROM as rom.bin"....but....where is the .bin file?

**Comment by GMMan** [comment]
The ROM is not included for copyright reasons. You will have to find it yourself.

**Comment by fifammlaf** [comment]
xfw or flipper zero Xtreme firmware includes the rom.bin
