### ISSUE TITLE
Timer actually saves from save point?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [GMMan/flipperzero-tamagotch-p1#8]
Is it possible to make it use real time? It is way behind my time now. Or is there a way to change the timer after setting it?

**Comment by zcbml88** [comment]
Yes, on the main screen press the down arrow to open the clock. Then press the up arrow to open the menu. select option A+C and click ok. Now click the back arrow and change the time on the clock using left arrow for hours and down for minutes. Then press up arrow again to open the menu. Select A+C again to finish setting the time. 
But unfortunately there isn't a way to keep the time synced in background for when app is closed.

**Comment by ZekePolarisBSH** [comment]
Ohhhhhh so that's how on this, thanks my dude
